<?php
/* ************************
    BIBLIOTECA DE DEFINICIONS
	AUTOR: TONI LÓPEZ
	ANY: 2013
***************************  */

/* IP centre */
define("IP_CENTRE", "127.0.0.1");

/* SMS's */
// CAPÇALERA QUE DESITGES TENIR AL MISSATGE. SENSE ESPAIS I UN MÀXIM DE 12 CARÀCTERS
define("HEADER_SMS", "INSPROVA");
// USUARI QUE S'HA SUBMINISTRAT AL DONAR D'ALTA EL CENTRE EN EL SERVEI DE SMS
define("USERNAME_SMS", "insproNmJhcB");
// CODI QUE S'HA SUBMINISTRAT AL DONAR D'ALTA EL CENTRE EN EL SERVEI DE SMS
// VIGILEU A QUI LLIUREU AQUEST CODI I QUI HI TÉ ACCÉS, ÉS L'ELEMENT BÀSIC PER L'ENVIAMENT DEL SMS
define("PASSWD_SMS", "tkCCyYbK");

/* Tipus Falta Alumne */
define("TIPUS_FALTA_ALUMNE_ABSENCIA", 1);
define("TIPUS_FALTA_ALUMNE_RETARD", 2);
define("TIPUS_FALTA_ALUMNE_JUSTIFICADA", 3);
define("TIPUS_FALTA_ALUMNE_SEGUIMENT", 4);
define("TIPUS_FALTA_ALUMNE_SORTIDA", 5);
define("TIPUS_FALTA_ALUMNE_CCC", 6);
define("TIPUS_FALTA_ALUMNE_MULTIPLE", 7);

/* Tipus Falta Professor */
define("TIPUS_FALTA_PROFESSOR_ABSENCIA", 1);
define("TIPUS_FALTA_PROFESSOR_RETARD", 2);
define("TIPUS_FALTA_PROFESSOR_JUSTIFICADA", 3);
define("TIPUS_FALTA_PROFESSOR_SORTIDA_AMB_ALUMNES", 4);

/* Tipus Càrrecs */
define("TIPUS_TUTOR", 1);
define("TIPUS_COORDINADOR", 2);
define("TIPUS_ADMINISTRADOR", 3);
define("TIPUS_SUPERADMINISTRADOR", 4);
define("TIPUS_CONSERGE", 5);

/* Tipus Accions desenvolupades al sistema */
define("TIPUS_ACCIO_LOGIN", 1);
define("TIPUS_ACCIO_LOGOUT", 2);
define("TIPUS_ACCIO_ENTRACLASSE", 3);
define("TIPUS_ACCIO_ENTRAGUARDIA", 4);
define("TIPUS_ACCIO_PASALLISTA", 5);
define("TIPUS_ACCIO_PASALLISTAGUARDIA", 6);
define("TIPUS_ACCIO_NOENTRACLASSE", 7);
define("TIPUS_ACCIO_ENTROALCENTRE", 8);
define("TIPUS_ACCIO_SURTODELCENTRE", 9);


//referencia generado con MD5(uniqueid(<some_string>, true))
define('API_KEY','3d524a53c110e4c22463b10ed32cef9d');


?>
